/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopologyAcronymRouteImport } from './routes/topology.$acronym'
import { Route as EditAcronymRouteImport } from './routes/edit.$acronym'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopologyAcronymRoute = TopologyAcronymRouteImport.update({
  id: '/topology/$acronym',
  path: '/topology/$acronym',
  getParentRoute: () => rootRouteImport,
} as any)
const EditAcronymRoute = EditAcronymRouteImport.update({
  id: '/edit/$acronym',
  path: '/edit/$acronym',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/edit/$acronym': typeof EditAcronymRoute
  '/topology/$acronym': typeof TopologyAcronymRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/edit/$acronym': typeof EditAcronymRoute
  '/topology/$acronym': typeof TopologyAcronymRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/edit/$acronym': typeof EditAcronymRoute
  '/topology/$acronym': typeof TopologyAcronymRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/edit/$acronym' | '/topology/$acronym'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/edit/$acronym' | '/topology/$acronym'
  id: '__root__' | '/' | '/edit/$acronym' | '/topology/$acronym'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditAcronymRoute: typeof EditAcronymRoute
  TopologyAcronymRoute: typeof TopologyAcronymRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topology/$acronym': {
      id: '/topology/$acronym'
      path: '/topology/$acronym'
      fullPath: '/topology/$acronym'
      preLoaderRoute: typeof TopologyAcronymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$acronym': {
      id: '/edit/$acronym'
      path: '/edit/$acronym'
      fullPath: '/edit/$acronym'
      preLoaderRoute: typeof EditAcronymRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditAcronymRoute: EditAcronymRoute,
  TopologyAcronymRoute: TopologyAcronymRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
